### ISSUE TITLE
General bugs

### ISSUE THREAD

**Issue by palletodap** [nschum/homebridge-twinkly#5]
Just got my Twinkly set up as last year, and again I installed this plugin to control the lights from HomeKit. But this time I have some strange bugs?

At first, HomeKit constantly shows no response, but I can control on/off and brightness?

I can't change the room for the light. 

When I force press into the light, brightness is always at 0%, but if I try to change it, it has no problem changing the brightness? - seems like an error doing get status of brightness. 

If anyone finds a solution or are able to modify the plugin to fix these issues please let me know.

**Comment by mensa84** [comment]
I have the same problem :(

**Comment by nschum** [comment]
Hi, the connection problems sound like the same problem as #4. Please try with the new version.

Are you still seeing the problem with changing the room? That's a strange one, since the plugin doesn't deal with room assignments. Maybe it's a consequence of the bad connection. Otherwise it could be a homebridge issue.

**Comment by palletodap** [comment]
The problem with room assignment is fixed after the latest update😄 Thanks🙏🏻

**Comment by mensa84** [comment]
Is there a changelog for the Twinkly-Homebridge Plugin?
